package softwarequalityGroup4;

import java.util.ArrayList;
import softwarequalityGroup4.Systems.SQSystem;
import softwarequalityGroup4.Systems.System1;
import softwarequalityGroup4.Systems.System2;
import softwarequalityGroup4.Systems.System3;
import softwarequalityGroup4.Systems.System4;
import softwarequalityGroup4.Systems.System5;

/**
 *
 * @author Nils
 */
public class GUI extends javax.swing.JFrame {

    private int componentCount;
    private String lambdaInput;
    private double[] lambdaI;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        componentsTextField = new javax.swing.JTextField();
        lambdaTextField = new javax.swing.JTextField();
        componentErrorLabel = new javax.swing.JLabel();
        lambdaErrorLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTextArea = new javax.swing.JTextArea();
        false1Box = new javax.swing.JCheckBox();
        false5Box = new javax.swing.JCheckBox();
        false2Box = new javax.swing.JCheckBox();
        false3Box = new javax.swing.JCheckBox();
        false4Box = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Anzahl der in Reihe geschalteten Komponenten n:");

        jLabel2.setText("Ausfallraten λ (1 pro Komponente; Trennen mit ´,´):");

        resultTextArea.setEditable(false);
        resultTextArea.setColumns(20);
        resultTextArea.setRows(5);
        jScrollPane1.setViewportView(resultTextArea);

        false1Box.setText("System 1");

        false5Box.setText("System 5");

        false2Box.setText("System 2");

        false3Box.setText("System 3");

        false4Box.setText("System 4");

        jLabel4.setText("Falsifizieren:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(componentsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(componentErrorLabel)
                            .addComponent(lambdaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lambdaErrorLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(false1Box)
                                    .addComponent(false5Box)
                                    .addComponent(false2Box)
                                    .addComponent(false3Box)
                                    .addComponent(false4Box)
                                    .addComponent(jLabel4))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(componentsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(componentErrorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lambdaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lambdaErrorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(9, 9, 9)
                        .addComponent(false1Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(false2Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(false3Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(false4Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(false5Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(startButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        componentErrorLabel.setText("");
        resultTextArea.setText("");
        lambdaInput = lambdaTextField.getText();

        try {
            if(componentsTextField.getText().equals("")){
                componentCount = 1;
            } else {
            componentCount = Integer.parseInt(componentsTextField.getText());
            }

        } catch (Exception e) {
            componentErrorLabel.setText("Ungültige Eingabe");
        }

        splitLambda();
        try {
            ArrayList<SQSystem> systemList = new ArrayList<SQSystem>();

            systemList.add(new System1(componentCount, lambdaI, false1Box.isSelected()));
            systemList.add(new System2(componentCount, lambdaI, false2Box.isSelected()));
            systemList.add(new System3(componentCount, lambdaI, false3Box.isSelected()));
            systemList.add(new System4(componentCount, lambdaI, false4Box.isSelected()));
            systemList.add(new System5(componentCount, lambdaI, false5Box.isSelected()));

            int[] resultArray = new int[5];

            for (int i = 0; i < 5; i++) {
                resultArray[i] = 0;
            }

            ArrayList<Double> results = new ArrayList<Double>();
            results.add(systemList.get(0).getReliabilityParameter());
            resultArray[0] = 1;

            for (int i = 0; i < systemList.size(); i++) {
                resultTextArea.append(String.valueOf("Reliability of system" + String.valueOf(i + 1) + " is " + systemList.get(i).getReliabilityParameter()) + "\n");

                int differentResults = 0;
                for (int j = 0; j < results.size(); j++) {
                    if (systemList.get(i).getReliabilityParameter() != results.get(j)) {
                        differentResults++;
                        
                    }
                }
                if (differentResults == results.size()) {
                    results.add(systemList.get(i).getReliabilityParameter());
                }
            }
            
            int differentResults = results.size();
            
            if(resultArray[2] >= 1 || (resultArray[0] > 1 && resultArray[0] > 1)){
                differentResults = 3;
            }

            String votingResult = "";
            switch (differentResults) {
                case 1:
                    votingResult = "Kein Fehler aufgetreten.";
                    break;
                case 2:
                    votingResult = "1 Fehler aufgetreten.";
                    break;
                default:
                    votingResult = "Mehrere Fehler aufgetreten";
                    break;

            }

            resultTextArea.append("\n" + votingResult + "\n");

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_startButtonActionPerformed

    private void splitLambda() {
        lambdaErrorLabel.setText("");
        String[] lambdas;

        try {
            lambdas = lambdaInput.split(",");
            lambdaI = new double[lambdas.length];

            for (int i = 0; i < lambdas.length; i++) {
                lambdas[i] = lambdas[i].replace(" ", "");
                lambdaI[i] = Double.parseDouble(lambdas[i]);
            }

            if (lambdas.length != componentCount) {
                throw new Exception();
            }

        } catch (Exception e) {
            lambdaErrorLabel.setText("Ungültige Eingabe");
            e.printStackTrace();
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel componentErrorLabel;
    private javax.swing.JTextField componentsTextField;
    private javax.swing.JCheckBox false1Box;
    private javax.swing.JCheckBox false2Box;
    private javax.swing.JCheckBox false3Box;
    private javax.swing.JCheckBox false4Box;
    private javax.swing.JCheckBox false5Box;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lambdaErrorLabel;
    private javax.swing.JTextField lambdaTextField;
    private javax.swing.JTextArea resultTextArea;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
